### ISSUE TITLE
Support for Persian language and RTL

### ISSUE THREAD

**Issue by HamidRezaSepehr** [bpampuch/pdfmake#758] opened 2016-11-23 07:09 UTC
I tried to use Persian strings instead of English ones, but no pdf is generated. Does pdfmake support Persian (or Arabic) language and RTL layout?

**Comment by liborm85** [comment] 2016-12-09 10:09
RTL currently it is not possible.

**Comment by liborm85** [comment] 2016-12-13 09:23
Duplicate of #184

**Closed by liborm85** 2016-12-13 09:23 UTC

**Comment by hbsoftco** [comment] 2020-09-13 19:56
+1
