### ISSUE TITLE
"page header" doc example doesn't seem to work

### ISSUE THREAD

**Issue by hujhax** [bpampuch/pdfmake#257] opened 2015-04-09 21:09 UTC
I'm guessing this is a problem with the docs rather than the code -- I tried entering the first "Headers and Footers" example from the documentation, like so:

    var doc = {
        header: 'simple text',

        footer: {
            columns: [
                'Left part', {
                    text: 'Right part',
                    alignment: 'right'
                }
            ]
        },

        content: "Content!"
    };

    pdfMake.createPdf(doc).open();

The result was a PDF that just had "Content!" on it, with no header or footer.  Hopefully I'm doing something simple wrong here?

**Comment by hujhax** [comment] 2015-04-09 21:11
Saving the file and opening it in FoxIt reader produced this: 
http://ft.trillian.im/0d2d46258c572aa7f4a70e4192df6de4690788fa/6xFy1LzUQ34MiXxlXVxUQEOYHjkwu.jpg

**Comment by hujhax** [comment] 2015-04-09 21:49
Hmm -- did some more poking around.  Seems to work in Firefox, but not in Chrome...

**Comment by hujhax** [comment] 2015-04-11 18:54
Aha -- looks like I can make it work by forcing header and footer to be functions, like so:


    var doc = {
        header: function() {return 'simple text',}

        footer: function( ) { return {
            columns: [
                'Left part', {
                    text: 'Right part',
                    alignment: 'right'
                }
            ]
        };},

        content: "Content!"
    };

    pdfMake.createPdf(doc).open();

**Comment by jthoenes** [comment] 2015-04-13 21:57
Hi, this is a duplicate of #227 - which has already been fixed but the fix has not been released yet.

**Closed by jthoenes** 2015-04-13 21:57 UTC

**Comment by hujhax** [comment] 2015-04-13 22:36
d'oh!  Sorry

**Comment by bpampuch** [comment] 2015-04-26 22:30
Done, 0.1.18 is out now

We're using webpack instead of browserify now so it should be easier to make custom builds

In order to build pdfmake, simply type: ```gulp``` or ```gulp build```

**Comment by hujhax** [comment] 2015-05-02 05:58
Great -- thanks!
