### ISSUE TITLE
Download doesn't work in Safari

### ISSUE THREAD

**Issue by robertmadsen** [bpampuch/pdfmake#208] opened 2015-02-21 05:05 UTC
pdfMake.createPdf(docDefinition).download

works great in FireFox, Chrome, and Internet Explorer, but does not work in Windows Safari. I haven't tested Mac Safari.

**Comment by jthoenes** [comment] 2015-02-21 09:17
Duplicate of #149

**Closed by jthoenes** 2015-02-21 09:17 UTC
