### ISSUE TITLE
Is this repository still active?

### ISSUE THREAD

**Issue by bhericher** [bpampuch/pdfmake#532] opened 2016-02-26 10:51 UTC
Just a question : have the devlopment switched to https://github.com/miltador/pdfmake2?

**Comment by ardean** [comment] 2016-02-28 19:11
+1

**Comment by miltador** [comment] 2016-02-29 09:21
@bhericher, @ardean that's just my fork were I accepted some pull request from this repo and fix bugs that I find while working with this library. I named it as pdfmake2 to indicate the continuation of development as this repo seems to be abandoned by original author.

**Comment by vbuser2004** [comment] 2016-02-29 21:26
Thanks for taking it on @miltador. It is a shame that this has repo has become stale as it is **needed** and it is **very useful**.

**Comment by likebrain** [comment] 2016-03-01 14:51
Thank @miltador, it's a shame nothing more happened.
The library is very cool. 

I have planned some new features. 
But what about the future here? 

Perhaps the development should be completely relocated?
The fork is a great thing! but he is also asleep when @miltador no longer working with the library?

Is it possible to find a new maintainer for this great project?

**Comment by dxvzzebw** [comment] 2016-03-01 15:27
First I would like to thank the contribiutors of pdfmake for the great work. Last activity of the maintainer has been on October 12, 2015. It seems he's not very active all the time.

@bpampuch An official statement about future plans would be helpful. There are really some people who use the library in production. It's really a pity that nothing progresses anymore. Possibly there will be someone who takes the job?

@miltador Could you explain your proposes with the new fork in advance? Is it something that will really grow, or only for your personal requirements?

**Comment by likebrain** [comment] 2016-03-01 15:47
I tried to reach today @bpampuch on Twitter.
Since October 2015, also here nothing happened. 

I think if the maintainer no longer "available" is should a mirror be created. 
This could be managed via a GitHub Organization so that something like this does not happen again in future. 

There are on the client side (browser) no good alternative with font embedding for this library. 
A restart with PDFKit would be verry sad and painful!

**Comment by miltador** [comment] 2016-03-01 16:04
@dxvzzebw,
I plan to add some new features, rewrite some strange\ugly parts and fix bugs. For now I use this library only in one my project, but it seems to be quite popular library and therefore I would give it a go and spend some free time on it.

@likebrain,
There are some pros and cons about "separating" into new repo.

Pros: we can choose maintainer and contributors to the repo and we can accept pull requests as well.

Cons: there is already an official site, pdfmake.org. As this repo is abondoned, people will be somehow confused of this repo and our fork, where to find it and so on. And we cannot update the site as well.
That's why I chose to rename my fork to pdfmake2 and we should definitely think of it too.

Beside that, I saw contributors of this repo besides it's owner @bpampuch. Seems to me they are not active too but it would be great to hear something from them in this thread.

**Comment by likebrain** [comment] 2016-03-01 19:33
I think we should give the contributors and the maintainers some time. 

But a Plan B would not be bad. 
Many people use PDFmake in production. 
Many come from jsPDF which is also sleeping. Furthermore jsPDF has no font-embedding.

If none announces itself I see only two solutions for great PDF in Javascript.
1. Complete mirror of the repository in a new repository with a new name
2. A new library based on PDFKit.

Both mean a lot of work. I would invest some time.

**Comment by vbuser2004** [comment] 2016-03-01 19:48
@likebrain - I agree that we should give current maintainers some time to respond. It is much better to continue on where they left off, especially if they do not wish to maintain it and are willing to pass control. 
If we have an active repo in some form, I am willing to invest time and expense of maintaining a demo website (something like pdfmake.org) if needed. I am also willing to work on documentation as there are many features that could be better explained.

**Comment by regexti** [comment] 2016-03-01 20:06
+1

**Comment by bpampuch** [comment] 2016-03-01 21:13
Guys, if you are willing to contribute I'll be glad to grant you
appropriate rights to this repo. I also intend to get some work done soon
:) There are two important things to be covered: pluggable architecture to
let anybody implement extensions. This should be quite easy. The other is a
complete rewrite of the Layout Engine to let pdfmake print pages
sequentially instead of doing all measurements for the whole document up
front. Initially this hadn't been possible because of pdfkit limitations
(ie. printing total # of pages on every page), but now it can be done. This
would solve memory-based issues.

**Comment by liborm85** [comment] 2016-03-02 07:09
I will be glad if you will continue the development of the library, because it we used in some projects. For this reason I made some fixies and improvements this in PRs.

**Comment by NSadava** [comment] 2016-03-02 09:31
@bpampuch is there any pdfMake library for Appcelerator/Titanium?

**Comment by mackadir** [comment] 2016-03-02 11:08
PDFMaker Can dynamically added to the picture?

**Comment by likebrain** [comment] 2016-03-02 15:46
@bpampuch, @miltador 
Thanks for the feedback but how to go from here?
What about the open PR in this repo?
What about the PDFMake2 Fork?

A few details about the next steps would be well.

Which repository should I now forking to develop new features?

**Comment by miltador** [comment] 2016-03-02 16:51
@likebrain,
I will create pull requests with my fixes and I'll delete my fork if my changes will be accepted here.

**Comment by emi58** [comment] 2016-03-03 12:55
I am also highly interested in a fix for the memory leak of the server side version of the library.
40 pages of PDF takes 50 seconds to generate.

**Comment by vipex** [comment] 2016-03-16 15:45
+1

**Comment by stretch4x4** [comment] 2016-03-16 22:15
We are using this epic library in our project and in the future will need some new features like super script and sub script, so I am more than happy to help contribute as well.

**Comment by liborm85** [comment] 2016-03-20 06:42
@bpampuch

Any progress in status development of the repository/library?
I am waiting for merge PRs and release new version, because I it using in my projects. And I need to know the future of the library for my next library improvements.

**Comment by 91K00** [comment] 2016-03-24 10:10
Hi everybody,
I am also interested to contribute to make evolve this wonderful library. Especially on Table generation to allow more styling options.

**Comment by focuspocus** [comment] 2016-04-14 11:20
Hello @bpampuch 
hello everybody

Currently we're using this great library to create PDFs in a project. We love the document templating approach and easy usage, But we get more and more error reports about crashes especially on iOS smart devices. The problem is the memory consumption while creating the PDF.
In your post on March 1, you wrote that you're working on the main pain points - memory based and performance issues... are there any news about that?

**Comment by atdiff** [comment] 2016-04-25 14:30
@bpampuch, curious of the status of the proposed changes and improvements.  I'd prefer to use pdfmake with the additional functionality and abilities, but I'd like to stick with something that is well maintained too.

**Comment by DataTables** [comment] 2016-05-17 16:41
Posting this here as the issues are off in the forked repo (understandably :-) ). I've just asked if @miltador's fork can be included on cdnjs on account of it having a number of fixes.

@miltador or @bpampuch - would you be interested in funded development of the library? Do you have the bandwidth (timewise) available for that? We could perhaps crowdfund fund for continued development and I'd be happy to kick it off.

**Comment by miltador** [comment] 2016-05-17 19:00
Hi everyone again!

First of all I want to say that my fork hasn't become that big and different yet to call it pdfmake2. 
I just forked the repo and included important pull requests from upstream along with my fixes too.
As I started to work with library and dug into the code I saw parts I didn't like and my intention was to rewrite some fundamental parts. Unfortunately last months I was busy with other projects in a bit other sphere (not web) so I hadn't even time to review pull requests to my fork.

But things have changed and my near future career will be in the web development and I think I can find some time to give my fork a go as I see the high demand for the library.

I also do not strongly insist on forking. As @bpampuch wrote, he can give rights to active community developers.

@DataTables interesting option but I've never worked this way. How do you see that funded development?

**Comment by DataTables** [comment] 2016-05-17 20:53
I've never worked with a crowd funded approach before myself to be honest, but it might be a good model to get development of pdfmake back up and running. While I can hopefully contribute a half decent little sum (~$1000?) it isn't going to pay for full time development of the software, but with others contributing, hopefully it can become worth your own or @bpampuch's time to spend a month or two working on the library to address current issues and improve performance (depending on your rates of course ;-) ). Depending on how you are setup for working on the software, perhaps a sprint would be the way to try it rather than a longer term commitment? (at least as the first phase!)

Very happy to talk open source development (its rewards and hazards) if you like - allan@{myHandle}.net.

My own open source library uses pdfmake [as an export option](https://datatables.net/extensions/buttons/examples/html5/simple.html) and it is hugely appreciated by the folks that use it - your work is awesome @bpampuch! Having pdfmake continue its development is beneficial for my own project and also for the others who have flagged their interest in this repo above.

**Comment by jww2000** [comment] 2016-05-17 23:27
I'm up for contributing money, I can't do thousands but I do all I can

**Comment by bhericher** [comment] 2016-05-18 06:47
I'm interested too by the idea of a crowfunding : I'll contribute as far as possible.

**Comment by tcsaddul** [comment] 2016-05-18 14:01
Me too. I'm in for crowd funding... Initially, I can contribute 300usd.  
 

    On Wednesday, May 18, 2016 2:48 PM, bhericher <notifications@github.com> wrote:
 

 I'm interested too by the idea of a crowfunding : I'll contribute as far as possible.—

**Comment by ffes** [comment] 2016-05-31 15:16
Forking the repo is in nobody's interest. Confusion all over the place.

I really hope @bpampuch will give @miltador access to the repo.

Maybe even better, create an organization (`pdfmake` seems still available, somebody should claim it before it is gone). This repo can be tranfered in thar organization. pdfmake.org seems to be hosted on GitHub pages. That repo should be moved to that organization as well.

Please @bpampuch, let this project continue as one and not as two!

**Comment by ffes** [comment] 2016-06-06 15:21
I just noticed that someone claimed the organization @pdfmake. Let's hope it is someone who is good-hearted to this project.

**Comment by miltador** [comment] 2016-06-07 14:30
@ffes that was me who created the organization @pdfmake. I've already started to work on the library and the first release is out - **v0.1.22**!

Check out the [repo](https://github.com/pdfmake/pdfmake/releases) to see the changelog. Also there are new packages available for [npm](https://www.npmjs.com/package/pdfmake-node), bower and [packagist](https://packagist.org/packages/pdfmake/pdfmake).

I think I will look through currently reported issues and will do myself a TODO list.

**To everyone:** feel free to join, submit your pull requests and help with development\testing\support\etc.
I think I will make a research of how the crowdfunding could be organized for those who want to donate to project.

**Closed** 2016-12-23 15:34 UTC
