### ISSUE TITLE
site down

### ISSUE THREAD

**Issue by mir-dhaka** [bpampuch/pdfmake#1329] opened 2018-03-21 16:21 UTC
http://pdfmake.org/ is down for a couple of days.
I am not able to get the playground. 
was it shifted to any other location?

**Comment by lerasah** [comment] 2018-03-21 16:37
Duplicate of Issue [#1321](https://github.com/bpampuch/pdfmake/issues/1321). There's a link to a temporary playground.

**Comment by KerimG** [comment] 2018-03-22 09:48
Yeah, the site's been down for a while. Does someone have an API reference?

**Closed** 2018-03-22 10:07 UTC
