### ISSUE TITLE
React-Native

### ISSUE THREAD

**Issue by jbcullis** [bpampuch/pdfmake#987] opened 2017-05-05 13:03 UTC
Using the library in React-Native works first call but fails on subsequent calls - "Attempting to change value of a readonly property"

**Comment by liborm85** [comment] 2017-05-08 05:53
Any example for reproduce your problem?

Something about React is described here: https://github.com/bpampuch/pdfmake/issues/939

**Comment by jbcullis** [comment] 2017-05-08 08:02
That one is about react.js, not react-native from what I can tell. Also a different issue, I have got it working but it will only allow me to call getBase64 once and will fail on subsequent calls.

I have uploaded what I'm doing to - https://github.com/jbcullis/RNPDF

**Comment by liborm85** [comment] 2017-05-08 15:09
I don't know how to build/run sample react-native project. But call pdfmake in https://github.com/jbcullis/RNPDF/blob/master/index.android.js#L12-L16 is probably correct.

What is writen in complete stack trace with error "Attempting to change value of a readonly property"? (This error may not be from pdfmake.)

**Comment by jbcullis** [comment] 2017-05-14 02:58
This is the error I see on the development server -
SyntaxError: Unexpected end of JSON input
    at parse (native)
    at process._tickCallback (internal/process/next_tick.js:103:7)
{ Error: write EPIPE
    at exports._errnoException (util.js:1026:11)
    at Socket._writeGeneric (net.js:710:26)
    at Socket._write (net.js:729:8)
    at doWrite (_stream_writable.js:333:12)
    at writeOrBuffer (_stream_writable.js:319:5)
    at Socket.Writable.write (_stream_writable.js:246:11)
    at Socket.write (net.js:656:40)
    at Socket.Writable.end (_stream_writable.js:479:10)
    at Socket.end (net.js:428:31)
    at Promise.resolve.then.then.then.catch.then.message (c:\Projects\RNPDF\node_modules\react-native\packager\src\Server\symbolicate\worker.js:35:33) code: 'EPIPE', errno: 'EPIPE', syscall: 'write' }

**Comment by liborm85** [comment] 2017-05-14 09:28
This error is not from pdfmake. You may have created a faulty JSON.

**Comment by jbcullis** [comment] 2017-05-14 10:32
Sort of, the error is being thrown by react, however it's being thrown when calling getBase64.
I'll need to put a couple days aside to tracing this one. I love this library and think it would be absolutely awesome for line of business apps built in libraries like react-native or xarmarin.....further I can run from rdlc, the happier I'll be.

**Comment by liborm85** [comment] 2017-05-21 09:13
Error `Attempting to change value of a readonly property` in React-Native looks similar as `Attempted to assign to readonly property` from issue #1005 in Ionic. The solution should be the same - clone docDefinition object because it's for some reason readonly (details: https://github.com/bpampuch/pdfmake/issues/1005#issuecomment-302877897).

**Comment by liborm85** [comment] 2017-06-02 10:07
No reaction.

**Closed by liborm85** 2017-06-02 10:07 UTC
Labels: waiting for information

**Comment by amorettimarcelo** [comment] 2018-10-14 14:32
Hey there! 
Have you solved it? If not, could you try to change the 'dd' from constant to variable?
in other words:
could you change from const dd = ...
to let dd = ...

hope it helps you.
