### ISSUE TITLE
headers and footers don't work anymore

### ISSUE THREAD

**Issue by natcohen** [bpampuch/pdfmake#268] opened 2015-04-21 08:48 UTC
I just updated to the new build and headers and footers don't work anymore... :(

**Comment by jthoenes** [comment] 2015-04-21 09:35
The issue is know and has been fixed with #227. 
Will be available with the next release. Use functions as work-arounds until then.

**Closed by jthoenes** 2015-04-21 09:35 UTC

**Comment by natcohen** [comment] 2015-04-21 19:51
Thanks, sorry for the duplicate... just to understand, how does versioning work? I can't find the version number and the website doesn't give any indication.

BTW, when do you plan to release the next version?

Thanks for the hard work!

**Comment by jthoenes** [comment] 2015-04-22 16:24
Have a look here: https://github.com/bpampuch/pdfmake/releases

There is no release planned at them moment, because we have an issue with browserify - so we cannot create a build file. @bpampuch is thinking about solutions

**Comment by bpampuch** [comment] 2015-04-26 22:26
Done, 0.1.18 is out now

We're using webpack instead of browserify now so it should be easier to make custom builds

In order to build pdfmake, simply type: ```gulp``` or ```gulp build```
