### ISSUE TITLE
Progress of pdf creation

### ISSUE THREAD

**Issue by emanuelschuetze** [bpampuch/pdfmake#837] opened 2017-01-23 14:22 UTC
I'm searching for a generic progress callback in pdfmake which gets the current progress while the pdf generation (in percentage). Then an application can show a progress bar of pdf creation. Such a user feedback is really required if you create huge pdf documents.

**Comment by lachok** [comment] 2017-02-01 17:35
I'd like this feature as well and have been looking at implementing it. The idea is to allow passing a `progressCallback` function in the options parameter to [`PdfPrinter.createPdfKitDocument`](https://github.com/bpampuch/pdfmake/blob/master/src/printer.js#L81). This will then be passed to [`renderPages`](https://github.com/bpampuch/pdfmake/blob/master/src/printer.js#L268).

In `renderPages` we can get the total number of items to be rendered and call the `progressCallback` every time a new item is rendered.

If this sounds like a good idea I'd be happy to do a pull request.

**Comment by liborm85** [comment] 2017-02-04 07:20
Merged PR https://github.com/bpampuch/pdfmake/pull/851

**Closed** 2017-02-11 13:42 UTC
Labels: feature request

**Comment by darrinholst** [comment] 2017-02-14 01:14
@lachok are you using this in the browser or server? I'm trying to use this server side and posting the progress to an external store (redis in this case) and it seems that the actual building of the pdf is all cpu bound so none of my I/O to redis gets processed until everything is done. In other words, I have a progress bar that goes directly from 0 to 100. Any ideas?

**Comment by lprusch** [comment] 2017-04-03 02:55
@darrinholst I've been trying to add a progress bar at client side (bootstrap) to pdfmake, but got the same issue you report. I've tried different sleep techniques inside the progressCallback function to try to let angular update the DOM, but no use. 

Also if I update the $scope var that holds the percentage only at 10% intervals (using $apply accordingly), to avoid too many $scope updates it still doesnt work. But if I hit a breakpoint each time the $scope is updated, then the progress bar updates by 10%. 

So the problem seems to be about what threads need to be suspended and how. Any ideas I could try?

**Comment by darrinholst** [comment] 2017-04-03 13:09
I looked at it for a few hours and couldn't find a solution. I'm thinking the problem is in pdfkit, not here, but I don't know for sure. It would be nice to have this work. Possibly related - https://github.com/devongovett/pdfkit/issues/269?
