### ISSUE TITLE
PDFMake not working on devices

### ISSUE THREAD

**Issue by girish-fuluskar** [bpampuch/pdfmake#677] opened 2016-08-23 09:28 UTC
Hi,

I am working on assignment where it require to generate PDF on devices (iOS, Android, Windows). I am using PDFMake library for the same, were I am able to generate the PDF on chrome but when I am running the same solution on any device. It doesn't work.

Kindly advice.

Girish

**Comment by hutch120** [comment] 2016-08-24 01:17
Hi Girish,

It's great you are engaging with the community to report an issue. 

With respect, you will likely get a better response from the community and collaborators if you at least have a crack at figuring out why the issue is occurring. Consider providing technical details of the devices you are testing with, things you have tried, what exactly isn't working.

Cheers,
Simon

**Comment by girish-fuluskar** [comment] 2016-08-24 05:52
Hi Simon,

Thanks for reply.
I am using PDFMake library in my Ionic application where I am creating pdf and using open() to open the pdf in viewer. All this works fine on browser (Mozilla and chrome) but when I install the app on android device, pdf doesn't open. I tried different approach and was able to open the pdf on android device through creating model and passing the blob url to it but that viewer not providing options for print and mail which generally comes in viewer.
So my question is, is there any way I can open my PDF in acrobat or in similar viewer?

Cheers,
Girish

**Comment by hutch120** [comment] 2016-08-24 06:14
Hi Girish,

IMHO the issue isn't really related to PDFMake, it is more a standards issue with how browsers implement their PDF viewers.

So then the answer becomes obvious, don't rely on browser implementation, instead, to ensure consistency between browsers use a PDF viewer library like pdf.js rather than rely on the built in PDF viewer.  https://mozilla.github.io/pdf.js/

Hope this helps. :)

**Comment by hutch120** [comment] 2016-08-31 23:18
Hi Girish,

Did you solve the problem? If so can you comment what you did and close this issue?

Cheers,
Simon

**Comment by liborm85** [comment] 2016-12-29 12:27
continued here: https://github.com/bpampuch/pdfmake/issues/800

**Closed by liborm85** 2016-12-29 12:27 UTC
