### ISSUE TITLE
Table: Uncaught Error when rowSpan and dontBreakRows combined

### ISSUE THREAD

**Issue by youssef11420** [bpampuch/pdfmake#2796] opened 2024-10-08 08:38 UTC
Hello,

I just updated the pdfmake package in my project to version 0.2.13 and I have an error when I use rowSpan on a table with `dontBreakRows: true`:
![image](https://github.com/user-attachments/assets/d41c6976-84cb-4b3b-bcb0-25f091c4c3f0)
![image](https://github.com/user-attachments/assets/f487962e-37de-4d54-98dc-8f27c221456b)

I also have the same error on a simple example in the playground:

```
var dd = {
	content: [
		{
			style: 'tableExample',
			color: '#444',
			table: {
				widths: [200, 'auto', 'auto'],
				headerRows: 2,
				dontBreakRows: true,
				// keepWithHeaderRows: 1,
				body: [
					[{text: 'Header with Colspan = 2', style: 'tableHeader', colSpan: 2, alignment: 'center'}, {}, {text: 'Header 3', style: 'tableHeader', alignment: 'center'}],
					[{text: 'Header 1', style: 'tableHeader', alignment: 'center'}, {text: 'Header 2', style: 'tableHeader', alignment: 'center'}, {text: 'Header 3', style: 'tableHeader', alignment: 'center'}],
					['Sample value 1', 'Sample value 2', 'Sample value 3'],
					[{rowSpan: 3, text: 'rowSpan set to 3\nLorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor'}, 'Sample value 2', 'Sample value 3'],
					['', 'Sample value 2', 'Sample value 3'],
					['Sample value 1', 'Sample value 2', 'Sample value 3'],
					['Sample value 1', {colSpan: 2, rowSpan: 2, text: 'Both:\nrowSpan and colSpan\ncan be defined at the same time'}, ''],
					['Sample value 1', '', ''],
				]
			}
		}
	]
}
```

No problem when using version 0.2.12.

Could you please fix this issue?

Thanks

**Comment by gvonjeetze** [comment] 2024-10-08 14:07
I have the same issue on one of my projects 
 0.2.12 working fine 
 0.2.13 not working

maybe following helps for your debugging:

current code which not working
`self.writer.contextStack[self.writer.contextStack.length - 1];`

on my debugging session I  found out that it looks like that there is one level more and must be some thing like this
`self.writer.contextStack[self.writer.writer.contextStack.length - 1];`

but this looks weird to me too :)

So I hope you can fix it soon :)

So far I will stick on the 0.2.12

Thx

**Comment by fe-cj** [comment] 2024-10-08 21:48
In 0.3.0-beta.10 is working fine. 
Seems like the issue is just in 0.2.13

**Comment by liborm85** [comment] 2024-10-09 06:33
Fixed by commit https://github.com/bpampuch/pdfmake/commit/5be7295142d81a13a03275cc7c4bcf85c284f54f.

**Closed** 2024-10-09 06:44 UTC
Labels: bug, pending release

**Comment by youssef11420** [comment] 2024-10-09 10:58
Thanks for the quick fix and release!
