### ISSUE TITLE
Object.isExtensible is not a function

### ISSUE THREAD

**Issue by Yangsou** [bpampuch/pdfmake#2362] opened 2021-11-10 08:32 UTC
After I run to download the pdf file, the Object has been removed property isExtensible.

**Comment by ColiZei** [comment] 2021-11-10 09:36
I have the same problem in a vue app with vuetify.

I tested 3 methods: 

```js
pdfMake.createPdf(dd).print();
pdfMake.createPdf(dd).open();
pdfMake.createPdf(dd).download();
```

pdfmake Version: 0.2.3
vue: 2.6.14
vuetify: 1.5.0

Anyone got a solution?

**Comment by Yangsou** [comment] 2021-11-10 09:42
I just downgraded version to 0.2.0 or 0.2.2

**Comment by ColiZei** [comment] 2021-11-10 09:45
Doesn't worked for me :(

**Comment by Andrea48h** [comment] 2021-11-10 09:47
Same here on a vue 2 project with vuex, reactivity stops working after a call to any of these methods. I also tested the methods getBase64 and getBlob with the same result. The error I get is "TypeError: Object.isExtensible is not a function" every time I try to update the app state.

pdfmake Version 0.2.3
vue: 2.6.13
vuex: 3.6.2

I have downgraded to 0.2.2 for now.

**Comment by J3m5** [comment] 2021-11-10 11:12
I've been hit by this bug and solved it by reverting pdfmake back to version 0.2.2.

**Comment by liborm85** [comment] 2021-11-10 12:48
Please create runnable example for reproduce, eg. on https://jsfiddle.net/ or other. Thanks.

**Comment by Andrea48h** [comment] 2021-11-10 13:17
> Please create runnable example for reproduce, eg. on https://jsfiddle.net/ or other. Thanks.

quick example on jsfiddle: [https://jsfiddle.net/swvqy7km/4/](https://jsfiddle.net/swvqy7km/4/)

**Comment by J3m5** [comment] 2021-11-10 13:24
> quick example on jsfiddle: https://jsfiddle.net/swvqy7km/4/

So it's not even related to Vue, it looks like the global Object prototype is modified by replacing the isExtensible function by an object literal.

**Comment by Andrea48h** [comment] 2021-11-10 13:27
Yes I think so, I just noticed it using Vue because reactivity stops working, I see how it could have gone undetected otherwise

**Comment by Andrea48h** [comment] 2021-11-10 13:27
> > quick example on jsfiddle: https://jsfiddle.net/swvqy7km/4/
> 
> So it's not even related to Vue, it looks like the global Object prototype is modified by replacing the isExtensible function by an object literal.

Yes I think so, I just noticed it using Vue because reactivity stops working, I see how it could have gone undetected otherwise

**Comment by liborm85** [comment] 2021-11-10 14:48
Fixed by commit https://github.com/bpampuch/pdfmake/commit/ae0074e14f5e3dd1a9c4dc1b39eaa6cb6c49bc6e. 3rd-library core-js library version 3.19.1 contains this bug.

**Comment by liborm85** [comment] 2021-11-10 14:49
Fix released in version 0.2.4.

Thanks for cooperation.

**Closed by liborm85** 2021-11-10 14:49 UTC
Labels: bug, pending release

**Comment by Andrea48h** [comment] 2021-11-10 14:58
I have just upgraded to 0.2.4 and it does work as expected. Thanks for the very quick fix!

**Comment by J3m5** [comment] 2021-11-10 15:01
Upgraded and issue is gone.
Thanks for the fix!
