### ISSUE TITLE
Feature Request: Support for bidirectional text

### ISSUE THREAD

**Issue by rodnolan** [bpampuch/pdfmake#56] opened 2014-07-25 15:05 UTC
This feature would make the library usable for generating PDFs in right-to-left languages such as Hebrew

**Comment by jthoenes** [comment] 2015-02-18 09:27
Duplicate of #184 

@paviad You probably need to adapt docMeasure.js and layoutBuilder and build a similar methods to ``DocMeasure.measureLeaf`` and ``LayoutBuilder.processLeaf`` (e.g. ``processLeaf right``).

**Closed by jthoenes** 2015-02-18 09:27 UTC
