### ISSUE TITLE
Firefox is is not downloading pdf

### ISSUE THREAD

**Issue by onbermejo** [bpampuch/pdfmake#122] opened 2014-10-30 15:46 UTC
I can not download pdf loaded in firefox.

You can see doing this:

1.- The configuration in firefox: Preview in Firefox: http://postimg.org/image/aarnfmei7/

2.- Go to http://pdfmake.org/playground.html and click: Style1, and the click download: http://postimg.org/image/lh5rkoahf/

After this, the browser get frozen.

I think, but not sure, that this error is new.

Thanks

**Comment by Wabbala** [comment] 2015-02-10 10:25
@onbermejo I had this issue as well, one way to deal with this is to use `pdfMake.createPdf(docDefinition).open()` instead of `pdfMake.createPdf(docDefinition).download()` this will force firefox to open a new tab/window and view the pdf in there.

**Comment by onbermejo** [comment] 2015-02-10 10:28
Thank you very much

**Comment by Wabbala** [comment] 2015-02-17 12:39
O btw, I found out that this issue is for firefox versions below 25. (As I also mentioned in #196). Using FF 25+ will solve this issue.

**Comment by jthoenes** [comment] 2015-02-17 12:43
Cool, I close the issue. If the issue is still present @onbermejo please let me know!

**Closed by jthoenes** 2015-02-17 12:43 UTC

**Comment by no-more** [comment] 2015-05-09 16:28
Hello,

I have the same issue in FF 37.0.2
Open works but not download function. There's no error in the console.

Thanks.
