### ISSUE TITLE
Thank you for creating this tool , I'v manged to change the pdf font  but still,  cant use language like hebrew(RTL), is this option possible ? 

### ISSUE THREAD

**Issue by gilhalfon** [bpampuch/pdfmake#341] opened 2015-06-25 15:58 UTC

**Comment by jthoenes** [comment] 2015-06-26 08:59
Duplicate of #184 - it's currently not possible.

**Closed by jthoenes** 2015-06-26 08:59 UTC

**Comment by saurabhgis** [comment] 2017-05-17 11:26
is RTL supported or not?

**Comment by Wabbala** [comment] 2017-05-17 18:58
Nope not yet...
