### ISSUE TITLE
Images shifted to left after first generation

### ISSUE THREAD

**Issue by npowis** [bpampuch/pdfmake#592] opened 2016-05-25 09:10 UTC
Hi,

I'm using the library to generate a pdf from an angular click event. The images are included as base64 encodes. The pdf is generated correctly when the click is fired the first time, however on all subsequential clicks all images in the pdf have been moved to the right by approximately 1/4 of the page width. The only way to get the pdf to generate correctly again is to force a page refresh. 

Is there an internal margin generated that I need to clear or a clean up command after generation?

**Comment by liborm85** [comment] 2016-12-23 12:05
Fix is included in the new version (0.1.22).

**Closed by liborm85** 2016-12-23 12:05 UTC

**Comment by michaelqiji** [comment] 2017-05-02 18:18
@liborm85 , the problem is still there. The first image is not being alignment centered, nor the margin. The image have no space between the page left edge, and I tried 0.1.28, 0.1.22, 0.1.18, all fail for the first image. In 0.1.28, all of the images have no margin and not being centered.
