### ISSUE TITLE
support right-to-left languages.

### ISSUE THREAD

**Issue by molywitman** [bpampuch/pdfmake#430] opened 2015-10-29 16:44 UTC
When pdfmake will support right-to-left languages?
I used       'Alef' "//fonts.gstatic.com/ea/alefhebrew/v4/Alef-Regular.ttf",
But it revers the text.

**Comment by liborm85** [comment] 2016-12-13 09:24
Duplicate of #184

**Closed by liborm85** 2016-12-13 09:24 UTC
