### ISSUE TITLE
Special Characters

### ISSUE THREAD

**Issue by ante-kaspar** [bpampuch/pdfmake#127] opened 2014-11-03 13:57 UTC
How can I generate a PDF with the following content:

	content: [
			'ASCII-1:  A B C D E F G H I J K L M N O P Q R S T U V W X Y Z',
			'ASCII-2:  a b c d e f g h i j k l m n o p q r s t u v w x y z',
			'ASCII-3:  0 1 2 3 4 5 6 7 8 9',
			'ASCII-4:  . , : ; - _ ! ? / " \' ` ^ ~ * + = \\ | # $ @ % & ( ) < > [ ] { }',
			'German:  Ä Ö Ü ä ö ü ß',
			'Czech-1:  Á Č Ď É Ě Í Ň Ó Ř Š Ť Ú Ů Ý Ž',
			'Czech-2:  á č ď é ě í ň ó ř š ť ú ů ý ž',
			'Romanian-1:  Ă Â Î Ş Ţ',
			'Romanian-2:  ă â î ş ţ',
			'Slovenian-1:  Č Š Ž',
			'Slovenian-1:  č š ž',
			'Slowak-1:  Á Ä Č Ď É Í Ľ Ĺ Ň Ó Ô Ŕ Š Ť Ú Ý Ž',
			'Slowak-2:  á ä č ď é í ľ ĺ ň ó ô ŕ š ť ú ý ž',
			'Special:  § ´ ² ³ ° µ €'
	]

**Comment by jthoenes** [comment] 2015-02-18 09:18
Duplicate of #165

**Closed by jthoenes** 2015-02-18 09:18 UTC
