### ISSUE TITLE
What browser is this compatible with? I can't seem to get it to work in IE9.

### ISSUE THREAD

**Issue by elielizondo21** [bpampuch/pdfmake#192] opened 2015-02-09 20:58 UTC
What browser is this compatible with? I can't seem to get it to work in IE9.

**Comment by jthoenes** [comment] 2015-02-17 13:18
Duplicate of #16

**Closed by jthoenes** 2015-02-17 13:18 UTC

**Comment by Wabbala** [comment] 2015-03-03 13:57
@elielizondo21 check my work around in #16
