### ISSUE TITLE
Styling tables depending on both row and column index 

### ISSUE THREAD

**Issue by bmihelac** [bpampuch/pdfmake#134] opened 2014-11-12 12:41 UTC
Currently ``vLineWidth`` methods receives ``i`` as  column index. I wonder if it would be possible to add row index as well. This will allow more complex layouts, ie: different width or no vertical lines in header rows.

**Comment by jthoenes** [comment] 2015-02-19 07:52
Duplicate of #197

**Closed by jthoenes** 2015-02-19 07:52 UTC
