### ISSUE TITLE
Image auto widths and columns

### ISSUE THREAD

**Issue by evu** [bpampuch/pdfmake#1109] opened 2017-08-18 10:38 UTC
I'm trying to create a simple 2-up image layout, so each image is 50% page width in two columns, however the 'auto' or '*' widths don't seem to work with images. Is there any way to achieve this without setting explicit widths for the images? Or if not, is it possible to get the width of the page so I can do the math myself?

**Comment by 7samurai** [comment] 2017-08-25 08:21
i habe the same problem. I try colums, but when i try width with images, i got an JS error 'Error: unsupported number: NaN' . Is there a way to define the width of the colum and then the column content?
 `columns: [
	        {
	          width: '50%',
	          image: 'unilogo'
	        },
	        {
	          width: '50%',
	          image: 'unilogo2'
	        }
    	]`

**Comment by ocastx** [comment] 2017-09-01 12:04
Seems to be duplicate of #1085

**Comment by liborm85** [comment] 2017-11-06 16:01
duplicate: https://github.com/bpampuch/pdfmake/issues/862

**Closed by liborm85** 2017-11-06 16:01 UTC
