### ISSUE TITLE
Font style not work  

### ISSUE THREAD

**Issue by truepatch** [bpampuch/pdfmake#211] opened 2015-02-24 18:45 UTC
[http://pdfmake.org/playground.html](http://pdfmake.org/playground.html) "Style 1"
```
	styles: {
		header: {
			fontSize: 18,
			bold: true        // work
		},
		subheader: {
			fontSize: 15,
			normal: true      // not work
		},
		quote: {
			italics: true     // not work
		},
		small: {
			fontSize: 8
		}
	}   
```
Browsers Chrome, FF

**Comment by jthoenes** [comment] 2015-02-24 19:21
Duplicate of #162

**Closed by jthoenes** 2015-02-24 19:22 UTC
