### ISSUE TITLE
New version 0.8.0 of PDFKit

### ISSUE THREAD

**Issue by jhqxbjjp** [bpampuch/pdfmake#685] opened 2016-08-29 12:34 UTC
Hello,

the new version [0.8.0](https://github.com/devongovett/pdfkit/releases/tag/v0.8.0) of PDFKit has recently been released.

![image](https://cloud.githubusercontent.com/assets/21309926/18051519/4279c538-6df5-11e6-9548-ef99ee65c1c0.png)

I've locally updated the dependency in [package.json](https://github.com/bpampuch/pdfmake/blob/master/package.json#L10). Afterwards i've made a new gulp-build without success. The following error occurred in [TTFFont.js#L451](https://github.com/devongovett/fontkit/blob/master/src/TTFFont.js#L451) of fontkit.

**Error: Variations require a font with the fvar, gvar, and glyf tables.**

Possibly does anyone know how to fix the problem? 

Thanks for your help.

**Comment by devongovett** [comment] 2016-08-29 23:30
Upgrading to use fontkit in pdfmake will be a larger task than just updating to PDFKit v0.8.0. [Looks like](https://github.com/bpampuch/pdfmake/blob/master/src/printer.js#L282) pdfmake doesn't use PDFKit's text method, opting to write to the PDF manually, and it uses a bunch of PDFKit internals that have changed. To take advantage of the new features, the easiest way forward is to use PDFKit's text method, with line wrapping turned off so you can control that yourselves.

As for the issue with opening fonts, it is caused by pdfmake's [generated font name](https://github.com/bpampuch/pdfmake/blob/master/src/fontWrapper.js#L42). Fontkit looks for a sub-font (in this case, a variation) with that postscript name, which doesn't exist in the font.

**Comment by devongovett** [comment] 2016-09-01 04:58
Made a PR https://github.com/bpampuch/pdfmake/pull/689

**Comment by npdexsvs** [comment] 2016-09-01 08:58
@devongovett Awesome! Thanks for the changes. An [error](https://travis-ci.org/bpampuch/pdfmake#L362) has occured during the build process. I can reproduce that behavior. The library is not runnable with the latest commit.

**Comment by devongovett** [comment] 2016-09-01 15:03
@npdexsvs that doesn't appear to be caused by my changes. It happens in other builds on Travis. Anyway, it's caused by [this line](https://github.com/bpampuch/pdfmake/blob/master/src/browser-extensions/pdfMake.js#L8).

**Comment by jhqxbjjp** [comment] 2016-09-01 17:36
@devongovett That is correct. It appears since this [commit](https://github.com/devongovett/pdfmake/commit/c4593bffa3a95817e14a3bdda05821a4b292ab76). If i deactivate the block for the build i got few more errors as a consequence of missing node modules. Have you tried to create a pdf after succeeded build with an initial repository?

I used the following default commands for building.

```
$ npm install
$ npm install -g grunt-cli
$ npm test
```

After installing the node modules the build seems to be okay but then i got the following console output during pdf generation in the browser.

pdfmake.js:58628: Uncaught TypeError: Cannot read property 'readUInt32BE' of undefined

It seems it is still not executable. I've done the build with your [fontkit](https://github.com/devongovett/pdfmake/tree/fontkit) branch of pdfmake.

**Comment by devongovett** [comment] 2016-09-01 17:41
Well, tests are passing on Travis, and my local machine. And I tried the dev server, and that works fine too.

**Comment by jhqxbjjp** [comment] 2016-09-02 14:25
@devongovett Yes indeed, the tests are running through. But if i deactivate that [commit](https://github.com/devongovett/pdfmake/commit/c4593bffa3a95817e14a3bdda05821a4b292ab76), which should be reverted by the way, the following errors occured.

```
WARNING in ./~/pdfkit/~/fontkit/~/restructure/src/EncodeStream.js
Module not found: Error: Cannot resolve module 'iconv-lite' in c:\Users\T.Weintz\Desktop\pdfmake-fontkit\node_modules\pdfkit\node_modules\fontkit\node_modules\restructure\src
@ ./~/pdfkit/~/fontkit/~/restructure/src/EncodeStream.js 12:12-33
 
WARNING in ./~/pdfkit/~/fontkit/~/restructure/src/DecodeStream.js
Module not found: Error: Cannot resolve module 'iconv-lite' in c:\Users\T.Weintz\Desktop\pdfmake-fontkit\node_modules\pdfkit\node_modules\fontkit\node_modules\restructure\src
@ ./~/pdfkit/~/fontkit/~/restructure/src/DecodeStream.js 6:12-33
 
ERROR in ./~/pdfkit/~/fontkit/~/brotli/dec/dictionary-browser.js
Module not found: Error: Cannot resolve module 'base64-js' in c:\Users\T.Weintz\Desktop\pdfmake-fontkit\node_modules\pdfkit\node_modules\fontkit\node_modules\brotli\dec
@ ./~/pdfkit/~/fontkit/~/brotli/dec/dictionary-browser.js 1:13-33
```

With the following steps the build has finished successfully.

1. Adds missing node modules in restructure module
```
cd pdfmake/node_modules/pdfkit/node_modules/fontkit/node_modules/restructure
npm install
```

2. Adds missing node module base64-js to brotli
```
cd pdfmake/node_modules/pdfkit/node_modules/fontkit/node_modules/brotli
npm install base64-js
```

3. Rebuild pdfmake
```
npm test
```

Afterwards the build is done without errors and i have done a simple test with the following code in the browser.

```HTML
<!doctype html>
<html lang='en'>
	<head>
		<meta charset='utf-8'>
		<title>Simple example</title>
		<script src='pdfmake-fontkit/build/pdfmake.js'></script>
		<script src='pdfmake-fontkit/build/vfs_fonts.js'></script>
	</head>
	<body>
		<script type="text/javascript">
			var docDefinition = { content: 'This is the content' };
			pdfMake.createPdf(docDefinition).download('doc.pdf');
		</script>
	</body>
</html>
```

The following errors occurred in the browser.

```
pdfmake.js:58628 
Uncaught TypeError: Cannot read property 'readUInt32BE' of undefined

index.html:12 
Uncaught TypeError: pdfMake.createPdf is not a function
```

The build and pdf generation works as expected without the fontkit commit. Maybe these findings are helpful.

**Comment by liborm85** [comment] 2016-12-13 13:35
https://github.com/bpampuch/pdfmake/pull/689 and fix https://github.com/bpampuch/pdfmake/pull/775 merged

**Comment by liborm85** [comment] 2016-12-23 07:07
New version released.

**Closed by liborm85** 2016-12-23 07:07 UTC
