### ISSUE TITLE
Colspan in header not preserved when header is repeated on second page.

### ISSUE THREAD

**Issue by SEGEEK** [bpampuch/pdfmake#652] opened 2016-07-27 18:02 UTC
You can see this by looking at the header in page 2 for the pdf generated by this code (just paste it into the [playground](http://pdfmake.org/playground.html))

```
var dd = {
    content: [{
                        style: 'tableExample',
                        table: {
                            headerRows: 1,
                            body: [
                                    [{text:'Header Summary', colSpan: 3, alignment: 'center'}, {}, {}],
                                    ['One value goes here', 'Another one here', 'OK?'],
                                    ['One value goes here', 'Another one here', 'OK?'],
                                    ['One value goes here', 'Another one here', 'OK?'],
                                    ['One value goes here', 'Another one here', 'OK?'],
                                    ['One value goes here', 'Another one here', 'OK?'],
                                    ['One value goes here', 'Another one here', 'OK?'],
                                    ['One value goes here', 'Another one here', 'OK?'],
                                    ['One value goes here', 'Another one here', 'OK?'],
                                    ['One value goes here', 'Another one here', 'OK?'],
                                    ['One value goes here', 'Another one here', 'OK?'],
                                    ['One value goes here', 'Another one here', 'OK?'],
                                    ['One value goes here', 'Another one here', 'OK?'],
                                    ['One value goes here', 'Another one here', 'OK?'],
                                    ['One value goes here', 'Another one here', 'OK?'],
                                    ['One value goes here', 'Another one here', 'OK?'],
                                    ['One value goes here', 'Another one here', 'OK?'],
                                    ['One value goes here', 'Another one here', 'OK?'],
                                    ['One value goes here', 'Another one here', 'OK?'],
                                    ['One value goes here', 'Another one here', 'OK?'],
                                    ['One value goes here', 'Another one here', 'OK?'],
                                    ['One value goes here', 'Another one here', 'OK?'],
                                    ['One value goes here', 'Another one here', 'OK?'],
                                    ['One value goes here', 'Another one here', 'OK?'],
                                    ['One value goes here', 'Another one here', 'OK?'],
                                    ['One value goes here', 'Another one here', 'OK?'],
                                    ['One value goes here', 'Another one here', 'OK?'],
                                    ['One value goes here', 'Another one here', 'OK?'],
                                    ['One value goes here', 'Another one here', 'OK?'],
                                    ['One value goes here', 'Another one here', 'OK?'],
                                    ['One value goes here', 'Another one here', 'OK?'],
                                    ['One value goes here', 'Another one here', 'OK?'],
                                    ['One value goes here', 'Another one here', 'OK?'],
                                    ['One value goes here', 'Another one here', 'OK?'],
                                    ['One value goes here', 'Another one here', 'OK?'],
                                    ['One value goes here', 'Another one here', 'OK?'],
                                    ['One value goes here', 'Another one here', 'OK?'],
                                    ['One value goes here', 'Another one here', 'OK?'],
                                    ['One value goes here', 'Another one here', 'OK?'],
                                    ['One value goes here', 'Another one here', 'OK?'],
                                    ['One value goes here', 'Another one here', 'OK?'],
                                    ['One value goes here', 'Another one here', 'OK?'],
                                    ['One value goes here', 'Another one here', 'OK?'],
                                    ['One value goes here', 'Another one here', 'OK?'],
                                    ['One value goes here', 'Another one here', 'OK?'],
                                    ['One value goes here', 'Another one here', 'OK?'],
                                    ['One value goes here', 'Another one here', 'OK?'],
                                    ['One value goes here', 'Another one here', 'OK?'],
                                    ['One value goes here', 'Another one here', 'OK?'],
                                    ['One value goes here', 'Another one here', 'OK?']
                            ]
                        }
                }
    ]
}
```

**Comment by harmic** [comment] 2016-08-09 00:47
Isn't this a duplicate of #470 ?

**Comment by SEGEEK** [comment] 2016-08-09 17:56
@harmic It appears so, I swear I looked for it before submitting a new issue but I didn't seem to find that one :(

**Comment by liborm85** [comment] 2016-12-26 15:41
Duplicate: https://github.com/bpampuch/pdfmake/issues/470

**Closed by liborm85** 2016-12-26 15:41 UTC
Labels: bug
