### ISSUE TITLE
'return' outside function from #453

### ISSUE THREAD

**Issue by s7726** [bpampuch/pdfmake#598] opened 2016-06-01 14:53 UTC
Trying to `gulp build` in a clean checkout (after `npm install`) I'm getting an error because of #453 .

```
$ gulp build
(node:6892) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
[07:10:55] Using gulpfile ~\git\pdfmake\gulpfile.js
[07:10:55] Starting 'build'...
[07:10:55] [webpack] Hash: df7683d7986404c22b3d
Version: webpack 1.13.1
Time: 80ms
     Asset     Size  Chunks             Chunk Names
pdfmake.js  1.79 kB       0  [emitted]  main
chunk    {0} pdfmake.js (main) 126 bytes [rendered]
    [0] ./src/browser-extensions/pdfMake.js 126 bytes {0} [built] [1 error]

ERROR in ./src/browser-extensions/pdfMake.js
Module parse failed: C:\pdfmake\src\browser-extensions\pdfMake.js 'return' outside of function (8:1)
You may need an appropriate loader to handle this file type.
SyntaxError: 'return' outside of function (8:1)
    at Parser.pp.raise (C:\pdfmake\node_modules\webpack\node_modules\acorn\dist\acorn.js:920:13)
    at Parser.pp.parseReturnStatement (C:\pdfmake\node_modules\webpack\node_modules\acorn\dist\acorn.js:1846:74)
    at Parser.pp.parseStatement (C:\pdfmake\node_modules\webpack\node_modules\acorn\dist\acorn.js:1719:19)
    at Parser.pp.parseBlock (C:\pdfmake\node_modules\webpack\node_modules\acorn\dist\acorn.js:1991:21)
    at Parser.pp.parseStatement (C:\pdfmake\node_modules\webpack\node_modules\acorn\dist\acorn.js:1735:19)
    at Parser.pp.parseIfStatement (C:\pdfmake\node_modules\webpack\node_modules\acorn\dist\acorn.js:1840:26)
    at Parser.pp.parseStatement (C:\pdfmake\node_modules\webpack\node_modules\acorn\dist\acorn.js:1717:19)
    at Parser.pp.parseTopLevel (C:\pdfmake\node_modules\webpack\node_modules\acorn\dist\acorn.js:1648:21)
    at Parser.parse (C:\pdfmake\node_modules\webpack\node_modules\acorn\dist\acorn.js:1616:17)
    at Object.parse (C:\pdfmake\node_modules\webpack\node_modules\acorn\dist\acorn.js:882:44)
 @ ./src/browser-extensions/pdfMake.js 1:37-125
[07:10:55] Finished 'build' after 475 ms
```

**Comment by disyam** [comment] 2016-06-02 02:08
+1

**Comment by tsiegleauq** [comment] 2016-08-23 10:00
I face the same problem.
Is there any solution? I cannot make a patch since I cannot even build the project

**Comment by panfilov-vladislav** [comment] 2016-09-07 10:19
Same problem.
Suppose something wrong with this commit
https://github.com/bpampuch/pdfmake/commit/c4593bffa3a95817e14a3bdda05821a4b292ab76#diff-6386288eb50105455a10db38f5d24082

**Comment by tsiegleauq** [comment] 2016-09-07 10:22
this project seems detracted.
No commits for quite some time.
We changed to : https://github.com/pdfmake/pdfmake

**Comment by panfilov-vladislav** [comment] 2016-09-07 10:37
thx. 
The issue is irrelevant.
But maintainers should do something - provide a link to a new repo.
Also http://pdfmake.org still leads to this repo as well.

**Comment by tsiegleauq** [comment] 2016-09-07 10:40
I agree. However it seems that @bpampuch went inactive three two for month ago. So there is really not much maintainers can do

**Comment by liborm85** [comment] 2016-12-13 12:48
@tsiegleauq Some maintainers are found. :)

Fixed by https://github.com/bpampuch/pdfmake/pull/759

**Closed by liborm85** 2016-12-13 12:48 UTC
