### ISSUE TITLE
Errors on IOS v 9

### ISSUE THREAD

**Issue by blairjo** [bpampuch/pdfmake#935] opened 2017-04-01 09:04 UTC
I have an old IPhone 4 for testing and my angular site was working fine on IOS v 8.
Yesterday, I updated the phone to IOS V 9.3.5 and the site started to crash during the angular initialisation.

The error is coming from this code in pdfmake : 

```javascript
if (distance < 0) {
  throw new Error('[BrotliDecompress] invalid distance');
}
```

I don't have a mac to debug this so tracking the issue down is difficult (I got the error above from a friend's mac)

Here's what I know so far:
- On newer IOS devices it is fine
- On browsers it is fine
- On older IOS devices it is fine on v8
- The problem only occurs when running the grunt minified build - if I run the unbuilt source it is ok.

Is this a known issue?

Thanks

**Comment by elirov** [comment] 2017-04-11 14:24
Getting the same thing.  Going to try upgrading to 0.1.27 and see if that helps...

**Comment by blairjo** [comment] 2017-04-11 14:28
@elirov I had the same issue on 0.1.27 I think.
I have got round it for now by moving the pdf generation to the server instead, using the pdfmake node js library. There is a nice example showing how in the dev-playground folder in the source.

**Comment by elirov** [comment] 2017-04-11 14:31
Darn.. I was hoping they fixed it in 0.1.27.  What happens if we just comment out the if statement?  At least, until they fix the issue...

**Comment by blairjo** [comment] 2017-04-11 14:36
it's not that simple I'm afraid. That code snippet above is part of the BrotliDecompress library that is being sucked in as a dependency and browserified. 
I see the recent releases were to do with "webpack hacks" so my suspicion is that something odd is happening there. I don't use browserify or webpack though, so I don't know too much about them.

If I were you, if you are able to move your code to the server, I'd do that.

**Comment by liborm85** [comment] 2017-04-12 08:00
Some versions included "webpack hacks" because some fonts could not be loaded. It was fixed in new version `fontkit`.

`Brotli` is dependency of `fontkit` I do not know what to use it, but for this library I'm not create any webpack hacks.

**Comment by liborm85** [comment] 2017-04-12 08:16
I don't know where the problem is. I don't have iOS for testing...

**Comment by blairjo** [comment] 2017-04-12 09:07
I don't have access to a mac for debugging so I can't help too much either I'm afraid.
My best guess is that there is some conflict between the grunt minification process and whatever webpack does. I say that because if I don't minify the code it seems to work ok.

Having said that, I'm not sure it explains why it would work fine on IOS 10 / browsers etc..

**Comment by mnewmedia** [comment] 2017-04-18 14:38
Now I would like to join the club, and I have all the hardware required to debug this.
I have an ionic-1 Project where the error did occur, but I could read the error only 1-time, now it crashes even before I see any important logs.

While trying to figure out more, I did setup up an ionic-2 project and included `pdfmake` again. And see there in ionic-2 it works on `IOS9`perfectly fine.

So it has something todo with those module bundling stuff I'm not into it. In `ionic-2` they use webpack in `ionic-1` I use a gulpfile with browserify and tsify..

**Comment by ZaDarkSide** [comment] 2017-04-26 15:03
I have the same problem on iOS 9.3.5 iPad Mini, can anyone please fix this?

**Comment by liborm85** [comment] 2024-02-15 15:59
Follow here: https://github.com/foliojs/brotli.js/issues/18

**Closed by liborm85** 2024-02-15 15:59 UTC
Labels: bug, browser, 3rd-party
