### ISSUE TITLE
How to put controls (checkbox, textbox) while making pdf?

### ISSUE THREAD

**Issue by NeevShah** [bpampuch/pdfmake#146] opened 2014-11-29 08:44 UTC
I have requirement where I need to put checkbox control in pdf.. Do you support this functionality? How to do this? I'm sorry for my bad English.

**Comment by lvarayut** [comment] 2015-01-08 12:42
Did you already figure it out? I also need this functionality.

**Comment by jthoenes** [comment] 2015-02-18 09:41
Duplicate of #156

**Closed** 2015-02-18 09:41 UTC
Labels: feature request
