### ISSUE TITLE
The document title is showing in browser's title

### ISSUE THREAD

**Issue by mpsbhat** [bpampuch/pdfmake#1929] opened 2020-02-15 03:33 UTC
var dd = {
            info: {
                  title: 'awesome Document',
                  author: 'john doe',
                  subject: 'subject of document',
                  keywords: 'keywords for document',
            },
            content: 'This is an sample PDF printed with pdfMake'
      };

      pdfMake.createPdf(dd).print();

For the above sample doc, the title 'awesome Document' is showing correctly while using the pdfmake v0.1.29; When we upgraded the version to 2.0 along with appropriate vfs_fonts files the title is not showing. The document is rendered exactly as needed without any issues. Also the document metadata are not saved within meta properties while downloading the file in later case. Can someone suggest what is the mistake here?

**Comment by liborm85** [comment] 2020-02-16 08:05
What is version 2.0? How did you install it? You think 0.2? 

Tested with developed master branch where the version is marked as 0.2, and it is ok:
![image](https://user-images.githubusercontent.com/1298652/74601153-145ccb00-509b-11ea-8004-31a93939746a.png)

**Comment by liborm85** [comment] 2020-02-25 13:27
No reaction.

**Comment by mpsbhat** [comment] 2020-02-26 02:48
> What is version 2.0? How did you install it? You think 0.2?
> 
> Tested with developed master branch where the version is marked as 0.2, and it is ok:
> ![image](https://user-images.githubusercontent.com/1298652/74601153-145ccb00-509b-11ea-8004-31a93939746a.png)

It is `v0.2`, Sorry for typo error. We installed from downloading the build source. Also we updated the font file to include unicode font.

**Comment by liborm85** [comment] 2020-02-26 14:27
It works for me. Create some example e.g on https://jsfiddle.net/ for reproduce issue.

**Comment by mpsbhat** [comment] 2020-02-27 03:09
Here for your reference: https://jsfiddle.net/mpsbhat/13yzsjfL/4/

**Comment by liborm85** [comment] 2020-03-01 12:46
You are using too old master version. With actual master works ok: https://jsfiddle.net/3gbnmw4d/

**Closed by liborm85** 2020-03-01 12:46 UTC

**Comment by mpsbhat** [comment] 2020-03-02 08:24
Is there any effect on title by vfs_fonts file if vfs_fonts is updated with new fonts?

**Comment by liborm85** [comment] 2020-03-02 10:51
No, document title is not related to vfs_fonts file.
